image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_IMAGE: theconartist/spark-server

build:
  stage: build
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker login -u "$DockerUsername" -p "$DockerPassword"
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} theconartist/spark-server:latest
    - docker push ${CONTAINER_IMAGE}
  tags:
    - docker
